version: '3'
services:
  db:
    image: getjv/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - /home/rafael-brito/marco_aurelio\bases\mysql:/var/lib/mysql
  web:
    image: brancosmith/ubuntu
    ports:
      - "80:80"
    volumes:
      - /home/rafael-brito/marco_aurelio:/var/www/html
    links:
     - db

     
